spring:
  application:
    name: Backend
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2/console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gamesnap_db
    username: guest
    password: 123


  #
  #     driver-class-name: org.h2.Driver
  #     username: sa
  #     password:
  #     url: jdbc:h2:tcp://localhost/~/gamesnap
  #      최초 한번은 jdbc:h2/~/gamesnap로 접속 후 위와 같이 접속
  # GitIgnore 추가할거임!!!!!!!!!!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      # dialect: org.hibernate.dialect.H2Dialect
logging:
  org.hibernate.sql: debug

server:
  port: 1111
