# spring:
#   application:
#     name: Backend
#   # h2:
#   #   console:
#   #     enabled: true
#   #     path: /h2/console

#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/gamesnap_db
#     username: guest
#     password: 123

#   #
#   #     driver-class-name: org.h2.Driver
#   #     username: sa
#   #     password:
#   #     url: jdbc:h2:tcp://localhost/~/gamesnap
#   #      최초 한번은 jdbc:h2/~/gamesnap로 접속 후 위와 같이 접속
#   # GitIgnore 추가할거임!!!!!!!!!!
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         format_sql: true
#         use_sql_comments: true
#       # dialect: org.hibernate.dialect.H2Dialect
# logging:
#   org.hibernate.sql: debug

# server:
#   port: 1111

# 위에가 로컬 설정 아래가 AWS 설정
# test

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.183.85:3306/TEAM1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 1111 # 로컬에서 사용할 포트
